export enum InventoryKey {
  ID = 'id',
  PRODUCT_ID = 'productId',
  WAREHOUSE_ID = 'warehouseId',
  QUANTITY_ON_HAND = 'quantityOnHand',
  RESERVED_QUANTITY = 'reservedQuantity',
  REORDER_LEVEL = 'reorderLevel',
  MAX_STOCK_LEVEL = 'maxStockLevel',
  UNIT_COST = 'unitCost',
  LOCATION_CODE = 'locationCode',
  BATCH_NUMBER = 'batchNumber',
  EXPIRY_DATE = 'expiryDate',
  LAST_COUNTED_DATE = 'lastCountedDate',
  LAST_UPDATED = 'lastUpdated',
  UPDATED_BY = 'updatedBy',
  PRODUCT = 'product',
  WAREHOUSE = 'warehouse',
  AVAILABLE_QUANTITY = 'availableQuantity',
  IS_LOW_STOCK = 'isLowStock',
  IS_OVERSTOCK = 'isOverstock',
  TOTAL_VALUE = 'totalValue'
}
